### ISSUE TITLE
Allow specifying alternative store root

### ISSUE THREAD

**Issue by Thesola10** [nix-community/harmonia#254]
This would enable configs where the Nix store Harmonia is running off of contains secrets and other sensitive information, while Harmonia itself serves a separate store consisting only of build artifacts and non-sensitive info.

It should be equivalent to Nix's `--store` option, that is semantic paths should still extract to `/nix/store`, even if they're not physically stored there, like a sandboxed bind mount.

**Comment by Mic92** [comment]
Afaik it gets its setting from nix. You can probably define your own nix.conf and set `NIX_USER_CONF_FILES` to override it.

**Comment by Thesola10** [comment]
Unfortunately it doesn't honor it fully:
```
avril 03 00:13:32 Sirius harmonia[410]: [2024-04-02T22:13:32Z ERROR harmonia::nar] Error dumping path /nix/store/something-not-important.drv: Failed to get metadata for path: /nix/store/something-not-important.drv
avril 03 00:13:32 Sirius harmonia[410]:     
avril 03 00:13:32 Sirius harmonia[410]:     Caused by:
avril 03 00:13:32 Sirius harmonia[410]:         No such file or directory (os error 2)
```

It's trying to read the physical `/nix/store` even though Nix in the container was configured with store `local?root=/guest&read-only=1`

**Comment by Thesola10** [comment]
The issue also occurs with `/guest?read-only=1&real=/guest/nix/store`, meaning harmonia/libnixstore likely tries to pull paths from the _logical_ store rather than the _physical_ store.
